services:
  # Docker Hub: https://hub.docker.com/_/postgres
  # Github: https://github.com/postgres/postgres
  # Homepage: https://www.postgresql.org
  ai-hub-postgres:
    container_name: ai-hub-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    networks:
      ai-hub-postgres:
        ipv4_address: "10.118.16.2"
    dns: ["192.168.40.253"]
    environment:
      TZ: "Europe/Berlin"
      LANG: "de_DE.utf8"
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=de-DE"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: postgres
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.display.name=AI Hub - Postgres"
      - "wud.trigger.exclude=docker.autoupdate"
      - "wud.tag.include=^\\d+$"
      - "wud.link.template=https://www.postgresql.org/docs/release/$${major}.$${minor}"
    volumes:
      - ai-hub-postgres-data:/var/lib/postgresql

  # Docker Hub: https://hub.docker.com/r/dpage/pgadmin4
  # Github: https://github.com/pgadmin-org/pgadmin4
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      ai-hub-postgres:
        ipv4_address: "10.118.16.3"
    ports:
      - "5050:5050"
    environment:
      TZ: "Europe/Berlin"
      PGADMIN_DEFAULT_EMAIL: "julianreith@gmx.de"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_LISTEN_PORT: "5050"
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.display.name=AI Hub - PGAdmin"
      - "wud.tag.include=^latest$"
      - "wud.link.template=https://www.pgadmin.org/news/"
    volumes:
      - ai-hub-pgadmin-data:/var/lib/pgadmin

  # Docker Hub: https://hub.docker.com/_/adminer
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    networks:
      ai-hub-postgres:
        ipv4_address: "10.118.16.4"
    ports:
      - "2201:8080"
    environment:
      TZ: "Europe/Berlin"
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.display.name=AI Hub - Adminer"
      - "wud.tag.include=^latest$"
      - "wud.link.template=https://github.com/vrana/adminer/releases/tag/v$${major}.$${minor}.$${patch}"

networks:
  ai-hub-postgres:
    name: ai-hub-postgres
    ipam:
      driver: default
      config:
        - subnet: "10.118.16.0/20"
          gateway: "10.118.16.1"

volumes:
  ai-hub-postgres-data:
    name: ai-hub-postgres-data
  ai-hub-pgadmin-data:
    name: ai-hub-pgadmin-data
