services:
  # Docker Hub: https://hub.docker.com/r/hkotel/mealie
  # Github: https://github.com/mealie-recipes/mealie
  # Documentation: https://docs.mealie.io/documentation/getting-started/installation/backend-config/
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - "2144:9000"
    networks:
      mealie:
        ipv4_address: "10.24.44.2"
    dns: ["192.168.40.253"]
    environment:
      TZ: "Europe/Berlin"
      PUID: 1000
      PGID: 1000
      DEFAULT_GROUP: "Home"
      DEFAULT_HOUSEHOLD: "Family"
      BASE_URL: "https://mealie.3x3cut0r.de"
      TOKEN_TIME: 168 # hours
      API_PORT: 9000
      API_DOCS: "true"
      ALLOW_SIGNUP: "false"
      ALLOW_PASSWORD_LOGIN: "true"
      LOG_LEVEL: "info"
      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      # =====================================
      # OpenAI Config
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: "gpt-5-mini"
      # =====================================
      # Postgres Config
      # POSTGRES_USER: mealie
      # POSTGRES_PASSWORD: mealie
      # POSTGRES_SERVER: postgres
      # POSTGRES_PORT: 5432
      # POSTGRES_DB: mealie
      # =====================================
      # Email Configuration
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_FROM_NAME: "Mealie"
      SMTP_AUTH_STRATEGY: "TLS" # Options: 'TLS', 'SSL', 'NONE'
      SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.display.name=mealie"
      - "wud.trigger.include=docker.autoupdate"
      - "wud.link.template=https://github.com/mealie/releases/tag/$${major}.$${minor}.$${patch}"
    volumes:
      - mealie-data:/app/data/

networks:
  mealie:
    name: mealie
    ipam:
      driver: default
      config:
        - subnet: "10.24.44.0/24"
          gateway: "10.24.44.1"

volumes:
  mealie-data:
    name: mealie-data
